# Generated by Django 3.0.7 on 2020-07-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=100)),
                ("answer", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "active"), ("U", "unactive")],
                        default="ACTIVE",
                        max_length=8,
                    ),
                ),
            ],
        ),
    ]
