# Generated by Django 3.0.7 on 2020-07-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("UNACTIVE", "Unactive")],
                default="ACTIVE",
                max_length=8,
            ),
        ),
    ]
