# Generated by Django 3.0.7 on 2020-07-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0002_auto_20200716_0900"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=8,
            ),
        ),
    ]
